name: My Actions Test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
          TEST_ENV: World!
          Auther: PP
          FOLDER: ./
      
      - name: Build
        run: |
          mkdir out
          echo $TEST_ENV >> out/buildtest.ini
          echo "Hello World!" >> out/demo.ini

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: out
    
