name: My Actions Test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
          TEST_ENV: World!
          Auther: PP
          FOLDER: ./
      
      - name: Build
        run: |
          mkdir out
          echo $TEST_ENV >> out/buildtest.ini
          echo "Hello World!" >> out/demo.ini

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: out
          
      - name: Push Archive
        run:  |
          echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
          curl --location 'https://smee.io/ry3gFROw669JIrCi/webhook' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'fileurl=${{ steps.artifact-upload-step.outputs.artifact-url }}'
