name: My Actions Test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
          TEST_ENV: World!
          Auther: PP
          FOLDER: ./

      - name: Test Env
        run: |
          echo "TEST_VAR = ${{vars.TEST_VAR}}"
          echo "REPS_TEST_VAR = ${{vars.REPS_TEST_VAR}}"
          echo "TEST_SECRETS = ${{secrets.TEST_SECRETS}}"
          echo "REPS_TEST_SECRETS = ${{secrets.REPS_TEST_SECRETS}}"
      
      - name: Build
        run: |
          mkdir out
          echo $TEST_ENV >> out/buildtest.ini
          echo "Hello World!" >> out/demo.ini

      - name: Archive
        uses: actions/upload-artifact@v4
        id: artifact
        with:
          name: test
          path: out
          
      - name: Push Archive
        run:  |
          echo 'Artifact URL is ${{ steps.artifact.outputs.artifact-url }}'
          curl --location 'https://smee.io/ry3gFROw669JIrCi' \
                --header 'Authorization: ${{secrets.ACCESS_TOKEN}}' \
                --header 'Content-Type: application/x-www-form-urlencoded' \
                --data-urlencode 'fileurl=${{ steps.artifact.outputs.artifact-url }}'
          
